In [33]:
import numpy 
n=numpy.arange(27)

In [34]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [35]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [36]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [37]:
import cv2

In [38]:
img_g=cv2.imread("smallgray.png",0)#0=gray range , 1=RGB range
img_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [39]:
img_rgb=cv2.imread("smallgray.png",1)#0=gray range , 1=RGB range
img_rgb#the array is transpose the bottom left pixel is 187 Blue 198 Green and 209 Red (Its order like BGR)

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [40]:
cv2.imwrite("newpicgray.png",img_g)#create a pic based on the array

True

In [41]:
img_g[:,2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [42]:
img_g.shape

(3, 5)

In [43]:
img_g[2,4]

182

In [44]:
for i in img_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [45]:
for i in img_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [48]:
ims=numpy.hstack((img_g,img_g)#when a function want 1 argument and you need to give 2 like here you can sent them as a tuple

TypeError: unhashable type: 'numpy.ndarray'

In [49]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [52]:
lst=numpy.hsplit(ims,10)
lst

[array([[187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182]], dtype=uint8),
 array([[187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182]], dtype=uint8)]

In [55]:
lst=numpy.vsplit(ims,3)
lst

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)]